packages:
  - 'packages/*'
  - 'demos/*'
allowBuilds:
  core-js: false
  esbuild: true
overrides:
  serialize-javascript: ^7.0.6
  'vitepress>vite': ^6.4.3
  '@vitejs/plugin-vue>vite': ^6.4.3
minimumReleaseAgeExclude:
  - vitest-command-line
  - yargs-file-commands
  - '@vitest/coverage-v8'
  - '@vitest/mocker'
  - '@vitest/spy'
  - vitest
