import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { generatePages, parse, type OpenCliDocument } from '@clidoc/core';

export interface DocusaurusOptions {
  /** An OpenCLI document or a JSON/YAML filename relative to siteDir. */
  input: OpenCliDocument | string;
  /** Dedicated generated directory consumed by the Docusaurus docs plugin. */
  outputDir: string;
  basePath?: string;
}

const manifestName = '.clidoc-generated.json';
const legacyManifestName = '.opencli-generated.json';
function filename(id: string): string {
  return `clidoc-${createHash('sha256').update(id).digest('hex').slice(0, 20)}.md`;
}
async function previousFiles(outputDir: string, name: string, prefix: string): Promise<string[]> {
  try {
    const value: unknown = JSON.parse(await readFile(join(outputDir, name), 'utf8'));
    if (!Array.isArray(value)) throw new Error('Invalid generated file manifest');
    return value.filter(
      (entry): entry is string => typeof entry === 'string' && new RegExp(`^${prefix}-[a-f0-9]{20}\\.md$`).test(entry),
    );
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
}

/** Write CommonMark docs and remove only files recorded as generated by this package. */
export async function writeDocusaurus(document: OpenCliDocument, options: { outputDir: string; basePath?: string }) {
  const pages = generatePages(document, { basePath: options.basePath });
  await mkdir(options.outputDir, { recursive: true });
  const previous = await previousFiles(options.outputDir, manifestName, 'clidoc');
  const legacy = await previousFiles(options.outputDir, legacyManifestName, 'opencli');
  const current = pages.map((page) => filename(page.id));
  // Map each page's route to the generated filename holding it, so the landing page can link by
  // file instead of by route: Docusaurus then resolves the URL itself regardless of routeBasePath.
  const filenameByPath = new Map(pages.map((page, position) => [page.path, current[position]!]));
  for (const [position, page] of pages.entries()) {
    const frontmatter = [
      '---',
      'mdx:',
      '  format: md',
      `id: ${JSON.stringify(page.id)}`,
      `title: ${JSON.stringify(page.title)}`,
      `slug: ${JSON.stringify(page.path)}`,
      `sidebar_position: ${position + 1}`,
      '---',
      '',
    ].join('\n');
    const content =
      page.id === 'index'
        ? pages
            .slice(1)
            .reduce(
              (text, target) => text.replaceAll(`](${target.path})`, `](./${filenameByPath.get(target.path)})`),
              page.content,
            )
        : page.content;
    await writeFile(join(options.outputDir, current[position]!), frontmatter + content);
  }
  for (const name of [...previous, ...legacy])
    if (!current.includes(name)) await rm(join(options.outputDir, name), { force: true });
  await writeFile(join(options.outputDir, manifestName), JSON.stringify(current, null, 2) + '\n');
  await rm(join(options.outputDir, legacyManifestName), { force: true });
  return pages.map((page) => ({ type: 'doc' as const, id: page.id, label: page.title }));
}

/** Generate before content loading, so plugin-content-docs can discover the files. */
export default async function clidocPlugin(context: { siteDir: string }, options: DocusaurusOptions) {
  const document =
    typeof options.input === 'string'
      ? parse(await readFile(resolve(context.siteDir, options.input), 'utf8'))
      : options.input;
  await writeDocusaurus(document, {
    outputDir: resolve(context.siteDir, options.outputDir),
    basePath: options.basePath,
  });
  return { name: 'clidoc-docusaurus' };
}
