name: Deploy service

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
    secrets:
      GCP_SA_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GAR_HOSTNAME: us-central1-docker.pkg.dev
      PROJECT_ID: bhouston-general-hosting
      REGION: us-central1
      DOCKER_REGISTRY: shared-docker-registry
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud auth configure-docker ${{ env.GAR_HOSTNAME }} --quiet
      - name: Set image path
        run: echo "IMAGE_PATH=${{ env.GAR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.DOCKER_REGISTRY }}/${{ inputs.service_name }}:${{ github.sha }}" >> "$GITHUB_ENV"
      - uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_PATH }}
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.service_name }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_PATH }}
          flags: '--allow-unauthenticated'
